<?php

return [
    'paragraph_1' => '<b>Introduction</b><br/>Tesvan understands and respects our users’ need for privacy. This Privacy Policy describes the types of information we collect, the purposes for which it is used and how it is protected.<br/>The Policy applies to the personal information we collect when you use our Tesvan.com website. “Personal information” refers to any information that identifies or may potentially identify an individual. This includes your name, email, address, phone number, and other non-public information that is associated with such information.',
    'paragraph_2' => '<b>About Us</b><br/>Tesvan.com is a website for Tesvan LLC, an outsourcing and outstaffing Quality assurance service provider based in Armenia. In parallel with the information about our services and current projects, there is an educational part as well, which is created to help interested people get knowledge of QA and take their first steps in this domain.<br/>In this scope, Tesvan.com proposes free offline courses registration as well, where we need information collection the most.',
    'paragraph_3' => '<b>This Privacy Policy is created for the following points:</b><ol><li>Information We Collect and Receive About You</li><li>Information You Provide to Us</li><li>How We Use Your Information</li><li>How Long We Retain Information</li><li>How We Protect Your Information</li><li>Third-Party Services, Applications, and Websites</li><li>Changes to This Privacy Notice</li><li>Sharing Personal Information About You</li><li>Contacting us</li></ol>',
    'paragraph_4' => '<b>Information We Collect and Receive About You</b><br/>We collect the following information while you use our Services, and everything is done with your consent. In some cases, we receive information directly from you, such as your name, the company you work for, your education, location, and your work email address when you apply for our Services. We also receive information directly from you when you send us an email inquiry.',
    'paragraph_5' => '<b>Information You Provide to Us</b><br/>Information you fill while registering for our free courses or while applying for a job, as well as when you “contact us” for potential collaboration purposes.<br/>Information you provide in surveys – For our research purposes, sometimes we collect information such as your first and last name, email address, phone number, job title, and company name when you complete Tesvan surveys.<br/>Webinars – When attending our webinars online, you provide us with your email address, first and last name, phone number, job title, and position within your company or organization.',
    'paragraph_6' => '<b>How We Use Your Information</b><br/>We use collected information to:<ol><li>Communicate with you – We may contact you to respond to any of your inquiries, requests, and/or send important notices via email. This includes, for example, sending surveys to understand how you are using our services, providing you with customer support, or sending updates about new Service features if needed.</li><li>Provide and improve our Services – We use collected information to provide and analyze how you use our Services, develop new products and services, and improve functionality, quality, and user experience.</li><li>Market our Services – We use collected information to market our Services. We also combine personal information collected on our website with other information we collect online or offline about users to better tailor marketing or website content, including to measure the effectiveness of our advertising, or for other purposes, such as internal research.</li></ol>',
    'paragraph_7' => '<b>How Long We Retain Information</b><br/>All the information collected from you will be sorted to use in appropriate cases.<br/>The period for which we keep your information depends on the type of information.<br/>We will either delete or anonymize your information or, if this is not immediately practical then we will securely store your information and isolate it from further use until we can delete your data.',
    'paragraph_8' => '<b>How We Protect Your Information</b><br/>We use reasonable and appropriate physical, technical, and administrative security to protect your information from unauthorized use, access, loss, alteration, or destruction.',
    'paragraph_9' => '<b>Third-Party Services, Applications, and Websites</b><br/>Certain third-party services, websites, or applications you use or navigate to and from our Services, may have separate user terms and privacy policies that are independent of our Policy. This includes, for example, websites owned and operated by our customers or partners. We are not responsible for the privacy practices of these third-party services or applications. We recommend carefully reviewing the user terms and privacy statement of each third-party service, website, and/or application prior to use.',
];
